name: Run CasMonitor

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g localtunnel

      - name: Run CasMonitor with tunnel and show password
        run: |
          nohup python3 casmonitor.py > casmonitor.log 2>&1 &
          sleep 8
          # start localtunnel and capture its output
          lt --port 5000 --subdomain casmonitor-$GITHUB_RUN_ID > url.txt 2>&1 &
          sleep 5
          echo "Public URL (from url.txt):"
          cat url.txt || true
          # fetch and show the tunnel password (runner's public IP)
          echo "Tunnel password (use this to unlock loca.lt prompt):"
          curl -s https://loca.lt/mytunnelpassword || true
          echo "To access without the password via curl:"
          echo 'curl -H "bypass-tunnel-reminder: 1" https://casmonitor-'"$GITHUB_RUN_ID"'.loca.lt'
          echo "Keeping server alive for 8 minutes..."
          sleep 480
